In [1]:
import numpy as np

In [3]:
weight_vector = np.array([[1], [1], [1]])
x_vector = np.array([[3], [4], [5]])

In [5]:
weight_vector.T.dot(x_vector)

array([[12]])

In [8]:
import pandas as pd

In [10]:
data_url= 'data/housing.data'
df_data= pd.read_csv(data_url, sep='\s+', header = None)
df_data.columns = ['CRIM', 'ZN', "INDUS", "CHAS", "NOX", 'RM', "AGE", 'DIS', "RAD",'TAT', 'I', "AM",'GROOT','OMG']

In [11]:
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAT     I  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0  15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0  17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0  17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0  18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0  18.7   

       AM  GROOT   OMG  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [12]:
df_data['weight_0']=1

In [14]:
df_data=df_data.drop('CHAS', axis=1)

In [15]:
df_data.head()

CRIM    ZN  INDUS    NOX     RM   AGE     DIS  RAD    TAT     I      AM  \
0  0.00632  18.0   2.31  0.538  6.575  65.2  4.0900    1  296.0  15.3  396.90   
1  0.02731   0.0   7.07  0.469  6.421  78.9  4.9671    2  242.0  17.8  396.90   
2  0.02729   0.0   7.07  0.469  7.185  61.1  4.9671    2  242.0  17.8  392.83   
3  0.03237   0.0   2.18  0.458  6.998  45.8  6.0622    3  222.0  18.7  394.63   
4  0.06905   0.0   2.18  0.458  7.147  54.2  6.0622    3  222.0  18.7  396.90   

   GROOT   OMG  weight_0  
0   4.98  24.0         1  
1   9.14  21.6         1  
2   4.03  34.7         1  
3   2.94  33.4         1  
4   5.33  36.2         1

In [16]:
df_matrix= df_data.as_matrix()

C:\Users\multicampus\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [17]:
weight_vector = np.random.random_sample((14,1))

In [18]:
df_matrix.dot(weight_vector)

array([[593.70329959],
       [561.4087585 ],
       [553.10491373],
       [533.95875537],
       [542.17498114],
       [538.39200362],
       [607.15153846],
       [627.08655494],
       [619.70944769],
       [609.23233378],
       [617.97350473],
       [615.01908281],
       [590.38648278],
       [593.88886306],
       [589.34336673],
       [589.98169184],
       [570.34195332],
       [595.47980964],
       [487.11444912],
       [592.0051984 ],
       [595.10117123],
       [604.59919865],
       [610.04915303],
       [611.87896621],
       [607.94125667],
       [522.73473985],
       [590.5891896 ],
       [527.67754363],
       [602.31752252],
       [592.99033082],
       [579.12585394],
       [593.61933328],
       [462.64874715],
       [576.46912816],
       [480.74070313],
       [577.97144312],
       [558.82486501],
       [566.2928865 ],
       [560.09547394],
       [594.80779677],
       [592.8545304 ],
       [511.85010503],
       [511.54237069],
       [521

In [19]:
df_data.values.dot(weight_vector)

array([[593.70329959],
       [561.4087585 ],
       [553.10491373],
       [533.95875537],
       [542.17498114],
       [538.39200362],
       [607.15153846],
       [627.08655494],
       [619.70944769],
       [609.23233378],
       [617.97350473],
       [615.01908281],
       [590.38648278],
       [593.88886306],
       [589.34336673],
       [589.98169184],
       [570.34195332],
       [595.47980964],
       [487.11444912],
       [592.0051984 ],
       [595.10117123],
       [604.59919865],
       [610.04915303],
       [611.87896621],
       [607.94125667],
       [522.73473985],
       [590.5891896 ],
       [527.67754363],
       [602.31752252],
       [592.99033082],
       [579.12585394],
       [593.61933328],
       [462.64874715],
       [576.46912816],
       [480.74070313],
       [577.97144312],
       [558.82486501],
       [566.2928865 ],
       [560.09547394],
       [594.80779677],
       [592.8545304 ],
       [511.85010503],
       [511.54237069],
       [521