In [1]:
import numpy as np

### load txt

In [4]:
a = np.loadtxt('populations.txt')
a[:10]

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.]])

In [5]:
a_int = a.astype(int)
a_int[:3]

array([[ 1900, 30000,  4000, 48300],
       [ 1901, 47200,  6100, 48200],
       [ 1902, 70200,  9800, 41500]])

In [6]:
np.savetxt('int_data.csv', a_int, delimiter=",")

### numpy object -npy

In [7]:
np.save('npy_test', arr=a_int)

In [8]:
npy_array = np.load(file='npy_test.npy')
npy_array[:3]

array([[ 1900, 30000,  4000, 48300],
       [ 1901, 47200,  6100, 48200],
       [ 1902, 70200,  9800, 41500]])

In [9]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]], int)

In [10]:
np.savetxt('a_npy.txt',a)

In [12]:
a= np.loadtxt('a_npy.txt', dtype=int)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.savetxt('a_npy.csv', a)

In [14]:
a = np.loadtxt('a_npy.csv',dtype= int)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
b= np.array([[1,2,3], [4,5,6], [7,8,9]], int)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.save('bnpy', b)

In [17]:
b = np.load('bnpy.npy')

In [18]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])