In [1]:
import numpy as np

### boolean index

In [3]:
test_array = np.array([1,4,0,2,3,8,9,7], float)
test_array >3

array([False,  True, False, False, False,  True,  True,  True])

In [4]:
test_array[test_array >3]

array([4., 8., 9., 7.])

In [5]:
condition = test_array < 3
test_array[condition]

array([1., 0., 2.])

In [6]:
 A = np.array([
 [12, 13, 14, 12, 16, 14, 11, 10, 9], 
     [11, 14, 12, 15, 15, 16, 10, 12, 11], 
     [10, 12, 12, 15, 14, 16, 10, 12, 12], 
     [ 9, 11, 16, 15, 14, 16, 15, 12, 10], 
     [12, 11, 16, 14, 10, 12, 16, 12, 13], 
     [10, 15, 16, 14, 14, 14, 16, 15, 12], 
     [13, 17, 14, 10, 14, 11, 14, 15, 10], 
     [10, 16, 12, 14, 11, 12, 14, 18, 11], 
     [10, 19, 12, 14, 11, 12, 14, 18, 10], 
     [14, 22, 17, 19, 16, 17, 18, 17, 13], 
     [10, 16, 12, 14, 11, 12, 14, 18, 11], 
     [10, 16, 12, 14, 11, 12, 14, 18, 11], 
     [10, 19, 12, 14, 11, 12, 14, 18, 10], 
     [14, 22, 12, 14, 11, 12, 14, 17, 13], 
     [10, 16, 12, 14, 11, 12, 14, 18, 11]])     

B = A<15
B

array([[ True,  True,  True,  True, False,  True,  True,  True,  True],
       [ True,  True,  True, False, False, False,  True,  True,  True],
       [ True,  True,  True, False,  True, False,  True,  True,  True],
       [ True,  True, False, False,  True, False, False,  True,  True],
       [ True,  True, False,  True,  True,  True, False,  True,  True],
       [ True, False, False,  True,  True,  True, False, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True],
       [ True, False, False, False, False, False, False, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False, 

In [7]:
B.astype(np.int)

array([[1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 0, 1, 1, 1],
       [1, 1, 0, 0, 1, 0, 0, 1, 1],
       [1, 1, 0, 1, 1, 1, 0, 1, 1],
       [1, 0, 0, 1, 1, 1, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1]])

### fancy index

In [22]:
a = np.array([2,4,6,8], float)

In [23]:
a[a>4]

array([6., 8.])

In [27]:
a.take(2)

6.0

In [12]:
a = np.array([[1,4], [9,16]], float)
b = np.array([0,0,1,1,0], int)
c = np.array([0,1,1,1,1], int)
a[b,c]

array([ 1.,  4., 16., 16.,  4.])

In [13]:
a= np.array([[1,4], [9,16]], float)
a[b]

array([[ 1.,  4.],
       [ 1.,  4.],
       [ 9., 16.],
       [ 9., 16.],
       [ 1.,  4.]])